language: node_js

node_js:
  - 6.9.2
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

# Unit Tests (+code coverage)
script: yarn test
deploy:
  - provider: npm
    email: cem.moreau@gmail.com
    skip_cleanup: true
    api_key:
      secure: RcyMAGwdDOybxX0nK8kmX/r4TUEXdqabdaJDhorKcMCZRfrDh69Sst0YmPWelawLmTfOG9HKfikhxZxoDl49sGuxapXX/Tt4kfYJG7fHitGfBFNhLF6M9lOPaCx9kMLOAFAr5x4mDZIuEVS8D10jHVbZekYJYOaSy1sT2X04wDCZROyzVo3QZGwZTfUnZydRM1lxKLNlq68hewOzaSmxLyQqdwUm3qaw1hfdvdZ8Hyt8ux01XTTllBBFsYhqDVm/b0/9Geun7ZyVFMwtUfosgN4EHWxaeq+vB2+XQzvIF2huS1DNpABOpfSbzRGjL3ehXFAWOr3zxyaVdJVkArNCgYqpsnnqiGxXZD36UP+6jzlFk1xG0eVyzYdfBcuk3Vd90/jqEcvnLimGp1dmXzdyN/XZUL6zQCxqNvj0dIsEeSGIUYTwRbMmJuxqWkEHAfq0fK2V7cvfEf7H2NK000Xjaw9YpUiijyjbKCziYXE2M9f6URUUX7ka40A1zoYpaQ65X7I/rjxTvKXlPyl8xFlu4lP18G2qgmFJCFhRCQlWwVSRRmbpgz0dulJX1SdBuf9EfM3Dgibg/yEIJuxfuBk9TPOlHN53iZnBf9iiE46/A/r6IqDLlDofQIhHTS0iBut0nnl0FJBgNqx07bxIglCMDw/cfrakOuNa9BhoTRj3KTE=
    on:
      tags: true
      repo: duniter/duniter-prover
